package com.hkm.pozix.data.model

import kotlinx.serialization.Serializable

/** A timestamped caption segment returned by the transcript gateway. */
@Serializable
data class YoutubeTranscriptSegment(
    val id: String,
    val startMs: Long,
    val endMs: Long,
    val text: String
)

/**
 * Normalized transcript used by the AI pipeline.
 * Timestamps are provider data and must never be generated by the model.
 */
@Serializable
data class YoutubeTranscript(
    val videoId: String,
    val canonicalUrl: String,
    val language: String,
    val availableLanguages: List<String> = emptyList(),
    val provider: String = "supadata",
    val origin: String = "native_caption",
    val fetchedAt: Long = System.currentTimeMillis(),
    val segments: List<YoutubeTranscriptSegment> = emptyList()
)

/** Compact reference kept in chat history; the transcript itself lives in app-private storage. */
@Serializable
data class YoutubeSourceReference(
    val videoId: String,
    val canonicalUrl: String,
    val language: String,
    val segmentCount: Int,
    val provider: String,
    val origin: String,
    val transcriptPath: String,
    val fetchedAt: Long
)
